### ISSUE TITLE
added search parameters not working 

### ISSUE THREAD

**Issue by floriandeboissieu** [CS-SI/eodag-labextension#87]
Many thanks for this lab extension, very usefull to have a preview of available data!

I tested it with in order to preview some time series on a specific L1C tile, example "31TCJ".

In order to do that I know that there is a PEPS parameter "tileid" that can be used, so I added it as a search parameter (without defining any geometry), but it doesn't seem to be applied to the search as it gives more than 1e4 results. However, when I click on the "Apply" button, the code is all good, as well as the result outputing 4 images:
```
from eodag import EODataAccessGateway, setup_logging

setup_logging(1) # 0: nothing, 1: only progress bars, 2: INFO, 3: DEBUG

dag = EODataAccessGateway()
search_results, total_count = dag.search(
  productType="S2_MSI_L1C",
  start="2022-08-28",
  end="2022-09-03",
  cloudCover=100,
  tileid="31TCJ",
)
```

**Comment by sbrunato** [comment]
Hello @floriandeboissieu , and thanks for reporting this issue.

This has already been fixed with https://github.com/CS-SI/eodag-labextension/pull/82, be not yet deployed in a stable release. If you want to test it, you can install `eodag-labextension` [from sources ](https://github.com/CS-SI/eodag-labextension/blob/develop/CONTRIBUTING.md), or with `pip install git+https://github.com/CS-SI/eodag-labextension.git@develop`.

**Comment by floriandeboissieu** [comment]
Many thanks for your answer, I missed this fix and didn't try the develop branch (my bad...), it is working like a charm!
By the way, it would be even closer to perfect if it was possible to upload geometries (e.g. geodataframe object or file), but I post another issue on that.
Thanks again!
